MYRIAD_TOP = ../../..


.PHONY: all clean

# Myriad BDR system:
BUILD_SCRIPT := ./myriad-build.sh
DEPLOY_SCRIPT := ./myriad-deploy.sh
RUN_SCRIPT := ./myriad-run.sh


all:

clean:

include $(MYRIAD_TOP)/GNUmakesettings.inc
