MYRIAD_TOP = ../..

.PHONY: all clean clean-local

# Default do-nothing rule needed:
all:

clean: clean-local

clean-local:
	-@/bin/rm -f test-affin.dat *.png *.svg *.dat *.p


include $(MYRIAD_TOP)/GNUmakesettings.inc
