SIM_DIASCA_TOP = ..


.PHONY: all link-host-candidates

MODULES_DIRS = docker-images

all:


link-host-candidates:
	@cd $(SIM_DIASCA_TOP)/.. && $(MAKE) -s link-host-candidates


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
