MYRIAD_TOP = ../../../..

.PHONY: all


# As this module must be generated to share MyriadGUI OpenGL constants:
#
# (see the gui_constants and gui_opengl_constants modules, and the
# %_generated.beam target in GNUmakerules-automatic.inc)
#
EXTRA_BEAM_FILES = gui_opengl_generated.beam


include $(MYRIAD_TOP)/GNUmakesettings.inc
