MOCK_SIMULATORS_TOP = ../..


.PHONY: all


# Default do-nothing target:
all:
	@echo "   Please refer to the 'Sim-Diasca Dataflow HOWTO' for all information regarding the dataflow urban example."


include $(MOCK_SIMULATORS_TOP)/GNUmakesettings.inc
