% Copyright (C) 2022-2023 Olivier Boudeville
%
% This file is part of the Ceylan-Myriad library.
%
% This library is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License or
% the GNU General Public License, as they are published by the Free Software
% Foundation, either version 3 of these Licenses, or (at your option)
% any later version.
% You can also redistribute it and/or modify it under the terms of the
% Mozilla Public License, version 1.1 or later.
%
% This library is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
% GNU Lesser General Public License and the GNU General Public License
% for more details.
%
% You should have received a copy of the GNU Lesser General Public
% License, of the GNU General Public License and of the Mozilla Public License
% along with this library.
% If not, see <http://www.gnu.org/licenses/> and
% <http://www.mozilla.org/MPL/>.
%
% Author: Olivier Boudeville [olivier (dot) boudeville (at) esperide (dot) com]
% Creation date: Wednesday, February 23, 2022.


% These keyboard keycodes (i.e. gui_keyboard:keycode()) are directly coming from
% Loic Hoguin's esdl2 (see [1]:
% https://github.com/ninenines/esdl2/blob/master/include/sdl_keycode.hrl), which
% are themselves deriving in turn from Sam Lantinga's libSDL2 (see [2]:
% https://github.com/libsdl-org/SDL/blob/main/src/events/SDL_keyboard.c).

% Many thanks to both projects.

% Refer to the implementation notes in gui_keyboard.erl for all related
% information, notably for the differences between scancodes and keycodes.


% We prefer exposing uniform prefixes, and not pieces of some backends; so below
% is just [1], with the 'SDL' prefix replaced with the 'MYR_' one (for
% MyriadGUI); adding then 'K' for Keycode.

% Note that, with SDL, 'GUI' designates the former "Windows" key, we prefer
% naming it 'SUPER' (see https://en.wikipedia.org/wiki/Windows_key).


% Include guard:
-ifndef(__MYRIAD_UI_KEYBOARD_KEYCODES_HRL__).
-define(__MYRIAD_UI_KEYBOARD_KEYCODES_HRL__, 1).

% Mask of 0b100-0000-0000-0000-0000-0000-0000-0000:
-define(MYR_K_SCANCODE_MASK, (1 bsl 30)).

% From button to character (i.e. ensuring that bit 30 is set to 1):
-define(MYR_SCANCODE_TO_KEYCODE(SC), (SC bor ?MYR_K_SCANCODE_MASK)).


% Definitions of all known keycodes (a.k.a. on-keyboard characters that can be
% selected):

-define(MYR_K_RETURN, $\r).
-define(MYR_K_ESCAPE, $\033).
-define(MYR_K_BACKSPACE, $\b).
-define(MYR_K_TAB, $\t).
-define(MYR_K_SPACE, $ ).
-define(MYR_K_EXCLAIM, $!).
-define(MYR_K_QUOTEDBL, $").
-define(MYR_K_HASH, $#).
-define(MYR_K_PERCENT, $%).
-define(MYR_K_DOLLAR, $$).
-define(MYR_K_AMPERSAND, $&).
-define(MYR_K_QUOTE, $').
-define(MYR_K_LEFTPAREN, $().
-define(MYR_K_RIGHTPAREN, $)).
-define(MYR_K_ASTERISK, $*).
-define(MYR_K_PLUS, $+).
-define(MYR_K_COMMA, $,).
-define(MYR_K_MINUS, $-).
-define(MYR_K_PERIOD, $.).
-define(MYR_K_SLASH, $/).
-define(MYR_K_0, $0).
-define(MYR_K_1, $1).
-define(MYR_K_2, $2).
-define(MYR_K_3, $3).
-define(MYR_K_4, $4).
-define(MYR_K_5, $5).
-define(MYR_K_6, $6).
-define(MYR_K_7, $7).
-define(MYR_K_8, $8).
-define(MYR_K_9, $9).
-define(MYR_K_COLON, $:).
-define(MYR_K_SEMICOLON, $;).
-define(MYR_K_LESS, $<).
-define(MYR_K_EQUALS, $=).
-define(MYR_K_GREATER, $>).
-define(MYR_K_QUESTION, $?).
-define(MYR_K_AT, $@).
-define(MYR_K_LEFTBRACKET, $[).
-define(MYR_K_BACKSLASH, $\\).
-define(MYR_K_RIGHTBRACKET, $]).
-define(MYR_K_CARET, $^).
-define(MYR_K_UNDERSCORE, $_).
-define(MYR_K_BACKQUOTE, $`).
-define(MYR_K_a, $a).
-define(MYR_K_b, $b).
-define(MYR_K_c, $c).
-define(MYR_K_d, $d).
-define(MYR_K_e, $e).
-define(MYR_K_f, $f).
-define(MYR_K_g, $g).
-define(MYR_K_h, $h).
-define(MYR_K_i, $i).
-define(MYR_K_j, $j).
-define(MYR_K_k, $k).
-define(MYR_K_l, $l).
-define(MYR_K_m, $m).
-define(MYR_K_n, $n).
-define(MYR_K_o, $o).
-define(MYR_K_p, $p).
-define(MYR_K_q, $q).
-define(MYR_K_r, $r).
-define(MYR_K_s, $s).
-define(MYR_K_t, $t).
-define(MYR_K_u, $u).
-define(MYR_K_v, $v).
-define(MYR_K_w, $w).
-define(MYR_K_x, $x).
-define(MYR_K_y, $y).
-define(MYR_K_z, $z).
-define(MYR_K_CAPSLOCK, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CAPSLOCK)).
-define(MYR_K_F1, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F1)).
-define(MYR_K_F2, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F2)).
-define(MYR_K_F3, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F3)).
-define(MYR_K_F4, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F4)).
-define(MYR_K_F5, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F5)).
-define(MYR_K_F6, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F6)).
-define(MYR_K_F7, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F7)).
-define(MYR_K_F8, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F8)).
-define(MYR_K_F9, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F9)).
-define(MYR_K_F10, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F10)).
-define(MYR_K_F11, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F11)).
-define(MYR_K_F12, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F12)).
-define(MYR_K_PRINTSCREEN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_PRINTSCREEN)).
-define(MYR_K_SCROLLLOCK, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_SCROLLLOCK)).
-define(MYR_K_PAUSE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_PAUSE)).
-define(MYR_K_INSERT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_INSERT)).
-define(MYR_K_HOME, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_HOME)).
-define(MYR_K_PAGEUP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_PAGEUP)).
-define(MYR_K_DELETE, $\177).
-define(MYR_K_END, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_END)).
-define(MYR_K_PAGEDOWN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_PAGEDOWN)).
-define(MYR_K_RIGHT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_RIGHT)).
-define(MYR_K_LEFT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_LEFT)).
-define(MYR_K_DOWN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_DOWN)).
-define(MYR_K_UP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_UP)).
-define(MYR_K_NUMLOCKCLEAR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_NUMLOCKCLEAR)).
-define(MYR_K_KP_DIVIDE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_DIVIDE)).
-define(MYR_K_KP_MULTIPLY, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MULTIPLY)).
-define(MYR_K_KP_MINUS, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MINUS)).
-define(MYR_K_KP_PLUS, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_PLUS)).
-define(MYR_K_KP_ENTER, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_ENTER)).
-define(MYR_K_KP_1, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_1)).
-define(MYR_K_KP_2, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_2)).
-define(MYR_K_KP_3, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_3)).
-define(MYR_K_KP_4, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_4)).
-define(MYR_K_KP_5, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_5)).
-define(MYR_K_KP_6, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_6)).
-define(MYR_K_KP_7, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_7)).
-define(MYR_K_KP_8, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_8)).
-define(MYR_K_KP_9, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_9)).
-define(MYR_K_KP_0, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_0)).
-define(MYR_K_KP_PERIOD, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_PERIOD)).
-define(MYR_K_APPLICATION, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_APPLICATION)).
-define(MYR_K_POWER, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_POWER)).
-define(MYR_K_KP_EQUALS, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_EQUALS)).
-define(MYR_K_F13, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F13)).
-define(MYR_K_F14, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F14)).
-define(MYR_K_F15, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F15)).
-define(MYR_K_F16, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F16)).
-define(MYR_K_F17, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F17)).
-define(MYR_K_F18, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F18)).
-define(MYR_K_F19, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F19)).
-define(MYR_K_F20, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F20)).
-define(MYR_K_F21, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F21)).
-define(MYR_K_F22, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F22)).
-define(MYR_K_F23, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F23)).
-define(MYR_K_F24, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_F24)).
-define(MYR_K_EXECUTE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_EXECUTE)).
-define(MYR_K_HELP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_HELP)).
-define(MYR_K_MENU, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_MENU)).
-define(MYR_K_SELECT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_SELECT)).
-define(MYR_K_STOP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_STOP)).
-define(MYR_K_AGAIN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AGAIN)).
-define(MYR_K_UNDO, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_UNDO)).
-define(MYR_K_CUT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CUT)).
-define(MYR_K_COPY, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_COPY)).
-define(MYR_K_PASTE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_PASTE)).
-define(MYR_K_FIND, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_FIND)).
-define(MYR_K_MUTE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_MUTE)).
-define(MYR_K_VOLUMEUP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_VOLUMEUP)).
-define(MYR_K_VOLUMEDOWN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_VOLUMEDOWN)).
-define(MYR_K_KP_COMMA, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_COMMA)).
-define(MYR_K_KP_EQUALSAS400, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_EQUALSAS400)).
-define(MYR_K_ALTERASE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_ALTERASE)).
-define(MYR_K_SYSREQ, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_SYSREQ)).
-define(MYR_K_CANCEL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CANCEL)).
-define(MYR_K_CLEAR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CLEAR)).
-define(MYR_K_PRIOR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_PRIOR)).
-define(MYR_K_RETURN2, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_RETURN2)).
-define(MYR_K_SEPARATOR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_SEPARATOR)).
-define(MYR_K_OUT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_OUT)).
-define(MYR_K_OPER, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_OPER)).
-define(MYR_K_CLEARAGAIN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CLEARAGAIN)).
-define(MYR_K_CRSEL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CRSEL)).
-define(MYR_K_EXSEL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_EXSEL)).
-define(MYR_K_KP_00, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_00)).
-define(MYR_K_KP_000, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_000)).
-define(MYR_K_THOUSANDSSEPARATOR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_THOUSANDSSEPARATOR)).
-define(MYR_K_DECIMALSEPARATOR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_DECIMALSEPARATOR)).
-define(MYR_K_CURRENCYUNIT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CURRENCYUNIT)).
-define(MYR_K_CURRENCYSUBUNIT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CURRENCYSUBUNIT)).
-define(MYR_K_KP_LEFTPAREN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_LEFTPAREN)).
-define(MYR_K_KP_RIGHTPAREN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_RIGHTPAREN)).
-define(MYR_K_KP_LEFTBRACE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_LEFTBRACE)).
-define(MYR_K_KP_RIGHTBRACE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_RIGHTBRACE)).
-define(MYR_K_KP_TAB, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_TAB)).
-define(MYR_K_KP_BACKSPACE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_BACKSPACE)).
-define(MYR_K_KP_A, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_A)).
-define(MYR_K_KP_B, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_B)).
-define(MYR_K_KP_C, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_C)).
-define(MYR_K_KP_D, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_D)).
-define(MYR_K_KP_E, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_E)).
-define(MYR_K_KP_F, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_F)).
-define(MYR_K_KP_XOR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_XOR)).
-define(MYR_K_KP_POWER, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_POWER)).
-define(MYR_K_KP_PERCENT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_PERCENT)).
-define(MYR_K_KP_LESS, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_LESS)).
-define(MYR_K_KP_GREATER, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_GREATER)).
-define(MYR_K_KP_AMPERSAND, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_AMPERSAND)).
-define(MYR_K_KP_DBLAMPERSAND, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_DBLAMPERSAND)).
-define(MYR_K_KP_VERTICALBAR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_VERTICALBAR)).
-define(MYR_K_KP_DBLVERTICALBAR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_DBLVERTICALBAR)).
-define(MYR_K_KP_COLON, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_COLON)).
-define(MYR_K_KP_HASH, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_HASH)).
-define(MYR_K_KP_SPACE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_SPACE)).
-define(MYR_K_KP_AT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_AT)).
-define(MYR_K_KP_EXCLAM, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_EXCLAM)).
-define(MYR_K_KP_MEMSTORE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MEMSTORE)).
-define(MYR_K_KP_MEMRECALL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MEMRECALL)).
-define(MYR_K_KP_MEMCLEAR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MEMCLEAR)).
-define(MYR_K_KP_MEMADD, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MEMADD)).
-define(MYR_K_KP_MEMSUBTRACT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MEMSUBTRACT)).
-define(MYR_K_KP_MEMMULTIPLY, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MEMMULTIPLY)).
-define(MYR_K_KP_MEMDIVIDE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_MEMDIVIDE)).
-define(MYR_K_KP_PLUSMINUS, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_PLUSMINUS)).
-define(MYR_K_KP_CLEAR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_CLEAR)).
-define(MYR_K_KP_CLEARENTRY, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_CLEARENTRY)).
-define(MYR_K_KP_BINARY, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_BINARY)).
-define(MYR_K_KP_OCTAL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_OCTAL)).
-define(MYR_K_KP_DECIMAL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_DECIMAL)).
-define(MYR_K_KP_HEXADECIMAL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KP_HEXADECIMAL)).
-define(MYR_K_LCTRL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_LCTRL)).
-define(MYR_K_LSHIFT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_LSHIFT)).
-define(MYR_K_LALT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_LALT)).

% Preferred to LGUI:
-define(MYR_K_LSUPER, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_LSUPER)).

-define(MYR_K_RCTRL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_RCTRL)).
-define(MYR_K_RSHIFT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_RSHIFT)).

% Any shift:
-define(MYR_K_ANY_SHIFT, (?MYR_K_LSHIFT bor ?MYR_K_RSHIFT)).

-define(MYR_K_RALT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_RALT)).



% Preferred to RGUI:
-define(MYR_K_RSUPER, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_RSUPER)).

% "Alt Gr" key:
-define(MYR_K_MODE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_MODE)).

-define(MYR_K_AUDIONEXT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AUDIONEXT)).
-define(MYR_K_AUDIOPREV, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AUDIOPREV)).
-define(MYR_K_AUDIOSTOP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AUDIOSTOP)).
-define(MYR_K_AUDIOPLAY, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AUDIOPLAY)).
-define(MYR_K_AUDIOMUTE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AUDIOMUTE)).
-define(MYR_K_MEDIASELECT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_MEDIASELECT)).
-define(MYR_K_WWW, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_WWW)).
-define(MYR_K_MAIL, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_MAIL)).
-define(MYR_K_CALCULATOR, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_CALCULATOR)).
-define(MYR_K_COMPUTER, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_COMPUTER)).
-define(MYR_K_AC_SEARCH, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AC_SEARCH)).
-define(MYR_K_AC_HOME, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AC_HOME)).
-define(MYR_K_AC_BACK, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AC_BACK)).
-define(MYR_K_AC_FORWARD, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AC_FORWARD)).
-define(MYR_K_AC_STOP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AC_STOP)).
-define(MYR_K_AC_REFRESH, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AC_REFRESH)).
-define(MYR_K_AC_BOOKMARKS, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AC_BOOKMARKS)).
-define(MYR_K_BRIGHTNESSDOWN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_BRIGHTNESSDOWN)).
-define(MYR_K_BRIGHTNESSUP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_BRIGHTNESSUP)).
-define(MYR_K_DISPLAYSWITCH, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_DISPLAYSWITCH)).
-define(MYR_K_KBDILLUMTOGGLE, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KBDILLUMTOGGLE)).
-define(MYR_K_KBDILLUMDOWN, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KBDILLUMDOWN)).
-define(MYR_K_KBDILLUMUP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_KBDILLUMUP)).
-define(MYR_K_EJECT, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_EJECT)).
-define(MYR_K_SLEEP, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_SLEEP)).
-define(MYR_K_APP1, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_APP1)).
-define(MYR_K_APP2, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_APP2)).
-define(MYR_K_AUDIOREWIND, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AUDIOREWIND)).
-define(MYR_K_AUDIOFASTFORWARD, ?MYR_SCANCODE_TO_KEYCODE(?MYR_SCANCODE_AUDIOFASTFORWARD)).

-endif. % __MYRIAD_UI_KEYBOARD_KEYCODES_HRL__
