graph TD;

  PROP(Define the properties to be met)-->DET;
  DET(Determine a candidate system)-->SIM;
  SIM(Simulate its behaviour)-->RANK;
  RANK(Rank it)-->DET;
  RANK(Rank it)-->RET;
  RET(Retain it for proposal)
