MYRIAD_TOP = ../../..

.PHONY: all run

MODULES_DIRS = opengl


all:


run: gui_overall_run

# Run test-interactive to, well, perform actual interactive testing of base
# MyriadGUI services. Go to the 'opengl' subdirectory for all OpenGL-related
# testing.


include $(MYRIAD_TOP)/GNUmakesettings.inc
