SIM_DIASCA_TOP = ../../../../../..

.PHONY: all clean clean-local


all:

Test_probe.dat:
	@$(MAKE) -s class_Probe_run



clean: clean-local


clean-local:
	-@/bin/rm -f Per_*_Probe.plot Resource_Consumption_Probe_Over_*.plot



include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
