SIM_DIASCA_TOP = ../../../../../..

.PHONY: all real-clean real-clean-local

all:

real-clean: real-clean-local


real-clean-local:

#-@/bin/rm -rf Basic_probe_test-on-*


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
