SIM_DIASCA_TOP = ../../../../../..

.PHONY: all real-clean real-clean-local

# Refer to the web_result_management_test.erl test in
# sim-diasca/test/core/services/data-management/result-management for a test of
# web probes.


all:

real-clean: real-clean-local

real-clean-local:


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
