SIM_DIASCA_TOP = ../..


.PHONY: all


# At least for the 'clean' target:
MODULES_DIRS = sim-diasca-base-runtime-image sim-diasca-development-image \
			   sim-diasca-documentation-generation-image

all:

include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
