MOCK_SIMULATORS_TOP = ..

.PHONY: all info-plt


MODULES_DIRS = src test doc


PACKAGE_NAME := soda-test
PACKAGE_TOP  := $(MOCK_SIMULATORS_TOP)/$(PACKAGE_NAME)


all:


info-plt:
	@echo "PREDECESSOR_PLT_FILE = $(PREDECESSOR_PLT_FILE)"


include $(MOCK_SIMULATORS_TOP)/GNUmakesettings.inc
