MYRIAD_TOP = ../../..

.PHONY: all


# As these modules must be generated to share MyriadGUI constants:
#
# (see the gui_constants and gui_opengl_constants modules, and the
# %_generated.beam target in GNUmakerules-automatic.inc)
#
EXTRA_BEAM_FILES = gui_generated.beam gui_opengl_generated.beam


include $(MYRIAD_TOP)/GNUmakesettings.inc
