SIM_DIASCA_TOP = ../../../..

.PHONY: clean clean-local


clean: clean-local


clean-local:
	-@/bin/rm -f resilience-*-nodes.graph resilience-*-nodes.png


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
